Параллельное умножение матриц
bygu4/Semester3 pull request #1
Opened 2024-09-13 14:57 UTC by bygu4

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +// Copyright (c) 2024
вроде у MIT такое не нужно писать, а вот в apache нужно

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/MatrixMultiplier.cs
> +public static class MatrixMultiplier
Для статического класса плохое название "перемножитель матриц". По факту это просто сборище статических методов для перемножения, обычно юзают преписку Helper, Utils.

У вас тут получилось бы MatrixMultiplyUtils

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        $"../../../TestData/TestResults/";
Относительные пути это не очень хорошо. У людей с другими конфигурациями может не запуститься, лучше просто всю папку через настройки IDE отправлять в workdir тестов

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +    private static Stopwatch stopwatch = new ();
static stopwatch это базово плохая идея. Если вызовется два метода их использующих одновременно, то они повлияют на резы друг друга

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +    public static void MatrixMultiplierTest_BigData(
Название тестов не указывают на то, что делает тест, что он ожидает, для этого нужно вчитыватьс в код.

Часто юзают всякие названия уровня MatrixMultiply_WithBigData_ShouldReturnExpectedResult
За референсами можно пойти к Ирине Сазоновой или Ивану Похабову

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        stopwatch.Restart();
Мне кажется, что тесты все таки не про профилирование. Ладно если бы вы ставили какие-то верхние границы на время выполнения, но тут просто по факту объединили тестировни и замеры скорости. Из-за чего появилось много лишнего кода и стало тяжелее его читать

Предложение: вынести замеры в отдельный класс

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        Assert.That(sequentialProduct, Is.EqualTo(expectedProduct));
Давайте хотя бы один отступ между Act и Assert. Причина: легче для восприятия

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        Matrix left, Matrix right, Matrix expectedProduct)
если перенесли параметры на некст строку, то нужно каждый параметр с новой строки

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        ResultTable_WriteHeader();
Немного режет глаза. Все таки в C# принято для методом Паскаль кейс писать, а не аппер снейк кейс.
Для тестов скорее исключение, чтобы было проще читать предложения

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +            testResults.Average(x => Math.Pow(x - expectedValue, 2)));
строка не очень длинная, можно было не переносить на новую. Обычно переносят при >130 символах

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        Path.Join(TestResultsDirectory_Path, $"{DateTime.Now.Ticks}.txt");
Предлагаю в .gitignore добавить, у вас скорее всего уже дифф заспамило этими файлами

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplierTests.cs
> +        var concurrentProduct = MatrixMultiplier.MultiplyConcurrently(left, right);
Давайте разделим на два разных теста, чтобы было сразу видно, какой именно вид умножения упал

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/Matrix.cs
> +        this.Elements = elements;
`this.` на проде никто не пишет

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/Matrix.cs
> +            if (matrix == null || this.NumberOfRows != matrix.NumberOfRows ||
лучше использовать `matrix is null`. `is` нельзя переопределить и это точно сравнение с нулем. А как оно будет работать в самом методе Equals не очень очевидно

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/Matrix.cs
> +        return reader.ReadToEnd();
можно использовать FIle.ReadAllText и не делать отдельный приватный метод

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/Matrix.cs
> +    private void CopyToMatrix(string[] elements, int row)
Лучше чуть более говорящее название: `CopyElementsToRawInMatrix`

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/Matrix.cs
> +public class Matrix : IEquatable<Matrix>
для таких сущностей обычно лучше подходит `record`

2024-10-18 16:51 UTC, AlexPoziev commented on Tasks/MatrixMultiplication/MatrixMultiplication/MatrixMultiplier.cs
> +            i < (chunkIndex + 1) * chunkSize && i < product.Length; ++i)
тут тоже переход на новую строку страшно выглядит, лучше на той же оставить, символов не много

2024-12-03 12:13 UTC, yurii-litvinov requested changes
А ещё надо бы собственно результаты замеров (ту самую таблицу) выложить.

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/GlobalUsings.cs
> +// Copyright (c) 2024
Copyright чей? :) Надо указать автора в любом случае, просто Copyright не бывает

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplication.Tests.csproj
> +  </ItemGroup>
Пjдключите StyleCop.Analyzers ещё

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplyUtilsTests.cs
> +namespace Matrix.Tests;
namespace лучше первой содержательной строчкой (StyleCop как раз рекомендовал бы, если бы был включен)

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplyUtilsTests.cs
> +    private static string SmallData_CorrectCases_Path =
Оно тоже может быть const (или readonly), статические мутабельные поля меня очень пугают. И схема именования у них какая-то странная.

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplyUtilsTests.cs
> +        ResultTable_WriteTestResult(testCase, testResults, expectedValue, standardDeviation);
Не, всякие подсчёты статистик и формирование таблиц с результатами не надо делать в юнит-тестах, это отдельная задача. Лучше в Main прямо.

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplyUtilsTests.cs
> +namespace Matrix.Tests;
Корневой неймспейс по соглашению в .NET должен называться как проект, в котором он находится

2024-12-03 12:13 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication/Matrix.cs
> +        this.Elements = elements;
@AlexPoziev, я пишу и некоторые мои коллеги пишут (и StyleCop по умолчанию требует). Так что дело вкуса.

2024-12-25 20:33 UTC, yurii-litvinov approved these changes
Определённо лучше, чем было, так что зачтена

2024-12-25 20:33 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication.Tests/MatrixMultiplication.Tests.csproj
> +  </ItemGroup>
Не исправлено :)

2024-12-25 20:33 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication/MeasureResult/638700400102512946.txt
> +0 | 0.33333334 0 0 0 0 0 0 0 | 0.041666668 0.11023965
- Форматирование не очень
- Если матожидание приводится с точностью заметно большей, чем позволяет среднеквадратичное отклонение, тут беда с осознанием результатов
- Среднеквадратичное отклонение больше, чем матожидание — тут некоторая беда с постановкой эксперимента, его при таких условиях вообще нет смысла проводить, потому что мы не можем доверять данным

2024-12-25 20:33 UTC, yurii-litvinov commented on Tasks/MatrixMultiplication/MatrixMultiplication/Program.cs
> +    public static void Main()
Давно не надо писать Main явно

2025-04-12 17:38 UTC, merged