Lazy
bygu4/Semester3 pull request #2
Opened 2024-09-17 19:56 UTC by bygu4

2024-10-24 20:59 UTC, ArtyomKopan reviewed
3/5. Не рассмотрены плохие случаи, например, когда supplier выбрасывает исключение. Есть смысл сохранять это исключение в Lazy и выбрасывать его вместо ArgumentNullException, когда это потребуется

2024-10-24 20:59 UTC, ArtyomKopan commented on Tasks/Lazy/Lazy/SingleThreadLazy.cs
> +        if (this.isEvaluated)
если инвертировать условие, то можно сделать код чуть короче, и не потребуется дополнительный вызов метода после вычисления значения.

2024-10-24 20:59 UTC, ArtyomKopan commented on Tasks/Lazy/Lazy/ThreadSafeLazy.cs
> +    private bool isEvaluated = false;
нужно сделать поле isEvaluated volatile

2024-12-03 12:29 UTC, yurii-litvinov requested changes

2024-12-03 12:29 UTC, yurii-litvinov commented on Tasks/Lazy/Lazy.Tests/GlobalUsings.cs
> +// Copyright (c) 2024
Тут тоже надо бы написать автора

2024-12-03 12:29 UTC, yurii-litvinov commented on Tasks/Lazy/Lazy.Tests/Lazy.Tests.csproj
> +  </ItemGroup>
И тоже StyleCop включить

2024-12-03 12:29 UTC, yurii-litvinov commented on Tasks/Lazy/Lazy/ILazy.cs
> +public interface ILazy<T>
```suggestion
public interface ILazy<out T>
```
Если есть возможность указать вариантность генерика, всегда указывайте — пользователи спасибо скажут, когда будут `Lazy<object>` в метод передавать,

2024-12-03 12:29 UTC, yurii-litvinov commented on Tasks/Lazy/Lazy/SingleThreadLazy.cs
> +    private readonly Func<T> supplier = supplier;
Если он readonly, то нет смысла заводить для него поле, параметр основного конструктора становится полем и сам по себе. Однако он не должен быть readonly, и тогда без поля никак.

2024-12-03 12:29 UTC, yurii-litvinov commented on Tasks/Lazy/Lazy/SingleThreadLazy.cs
> +            this.EvaluateAndSaveResult();
После вычисления supplier надо занулить, чтобы дать сборщику мусора собрать его и всё, что попало ему в замыкание

2024-12-25 15:59 UTC, yurii-litvinov approved these changes
👍

2024-12-25 15:59 UTC, yurii-litvinov commented on Tasks/Lazy/Lazy/Lazy.csproj
> +    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118"/>
Лучше 1.2 бета

2025-04-12 17:40 UTC, merged